package com.massky.sraum.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.massky.sraum.bean.GateWayInfoBean;

import com.massky.sraum.bean.GateWayInfoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gateWayInfoBeanDaoConfig;

    private final GateWayInfoBeanDao gateWayInfoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gateWayInfoBeanDaoConfig = daoConfigMap.get(GateWayInfoBeanDao.class).clone();
        gateWayInfoBeanDaoConfig.initIdentityScope(type);

        gateWayInfoBeanDao = new GateWayInfoBeanDao(gateWayInfoBeanDaoConfig, this);

        registerDao(GateWayInfoBean.class, gateWayInfoBeanDao);
    }
    
    public void clear() {
        gateWayInfoBeanDaoConfig.clearIdentityScope();
    }

    public GateWayInfoBeanDao getGateWayInfoBeanDao() {
        return gateWayInfoBeanDao;
    }

}
